version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=voucher
      - DB_PASSWORD=Mysql*voucher
      - DB_NAME=sis_voucher
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8.0
    container_name: bd_voucher
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql*voucher
      - MYSQL_DATABASE=sis_voucher
      - MYSQL_USER=voucher
      - MYSQL_PASSWORD=Mysql*voucher
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge