version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: always
    volumes:
      - ./src:/app/src
    environment:
      - TZ=America/Sao_Paulo
    command: >
      /bin/sh -c "
      echo '🚀 Frontend is running at http://localhost';
      nginx -g 'daemon off;'"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=voucher
      - DB_PASSWORD=Mysql*voucher
      - DB_NAME=sis_voucher
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
      - TZ=America/Sao_Paulo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - ./mysql-backups:/app/mysql-backups
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    command: ["bun", "run", "src/server.js"]

  db:
    image: mysql:8.0
    container_name: bd_voucher
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=Mysql*voucher
      - MYSQL_DATABASE=sis_voucher
      - MYSQL_USER=voucher
      - MYSQL_PASSWORD=Mysql*voucher
      - TZ=America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-backups:/var/lib/mysql-backups
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --default-time-zone='-03:00'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "voucher", "-pMysql*voucher"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data:
    name: mysql_data

networks:
  app-network:
    driver: bridge