FROM oven/bun:1-debian

WORKDIR /app

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install --production

# Copy source code
COPY . .

# Expose API port
EXPOSE 5000

# Start the API server
CMD ["bun", "run", "src/server.js"]