services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fixed2
    ports:
      - "3000:80"
    volumes:
      - nginx_logs:/var/log/nginx
    environment:
      - NODE_ENV=production
      - TZ=America/Sao_Paulo
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs:
  app_data:
