// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjbydrcrksvmmpvslbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoamJ5ZHJjcmtzdm1tcHZzbGJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExODM1NzgsImV4cCI6MjA0Njc1OTU3OH0.R9SIFQMw12nRrlJLyd2hWH_cByqVtsbTw1iE2h-cP98";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});