name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: elmesson055/mealmantra-64
        ref: main
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
      
    - name: Run Tests
      run: |
        echo "No tests configured - passing step"
        exit 0
      
  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: elmesson055/mealmantra-64
        ref: main
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mealmantra:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mealmantra:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mealmantra:buildcache,mode=max
        
    - name: Deploy to Production Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mealmantra:latest
          docker stop mealmantra || true
          docker rm mealmantra || true
          docker run -d \
            --name mealmantra \
            -p 5000:5000 \
            --restart always \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e NODE_ENV=production \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/mealmantra:latest